var color = [
    "red",
    "green",
    "blue",
    "yellow",
    "orange",
    "rainbow",
    "brown",
    "black",
    "purple",
    "magenta",
    "almond",
    "rose",
    "amber",
    "aqua",
    "beige",
    "crimson",
    "lavender",
    "fuchsia",
    "gold",
    "silver",
    "indigo",
    "jade",
    "khaki",
    "mauve",
    "taupe",

    
];

var animal = [
    "monkey",
    "dog",
    "horse",
    "zebra",
    "sloth",
    "cat",
    "hummingbird",
    "parrot",
    "goose",
    "slug",
    "spider",
    "tarantula",
    "lion",
    "cheetah",
    "jaguar",
    "panther",
    "puma",
    "ocelot",
    "grouse",
    "hen",
    "rooster",
    "chicken",
    "penguin",
    "salmon",
    "tuna",
    "sparrow",
    "pigeon",
    "ferret",
    "aardvark",
    "albatross",
    "alligator",
    "anteater",
    "armadillo",
    "baboon",
    "badger",
    "barracuda",
    "bat",
    "bee",
    "butterfly",
    "camel",
    "buffalo",
    "crocodile",
    "duck",
    "elephant",
    "fox",
    "coyote",
    "gnat",
    "gazelle",
    "gorilla",
    "hamster",
    "rabbit",
    "ibex",
    "jellyfish",
    "emu",
    "lobster",
    "crab",
    "trilobite",
    "squid",
    "anglerfish",
    "hermit crab",
    "sponge"
];

var appliance = [
    "dishwasher",
    "microwave",
    "crisper",
    "waffle iron",
    "toaster",
    "oven",
    "television",
    "radio",
    "refrigerator",
    "cabinet",
    "washcloth",
    "towel",
    "dryer",
    "washing machine",
    "ironing board",
    "garment steamer",
    "toothpaste",
    "robot vacuum",
    "vacuum",
    "plunger",
    "bath mat",
    "laptop",
    "cell phone",
    "sattelite",
    "sponge",
    "ottoman",
    "couch"
]

var random = function(array){
    return array[Math.floor(Math.random() * array.length)]
}

var PurpleMonkeyDishwasher = function(){
    var randColor = random(color);
    var randAnimal = random(animal);
    var randAppliance = random(appliance);
    return randColor + " " + randAnimal + " " + randAppliance
}
module.exports = PurpleMonkeyDishwasher;